import {
  GraphQLObjectType,
  GraphQLID,
  GraphQLString,
  GraphQLInt,
  GraphQLBoolean,
  GraphQLFloat,
} from "graphql";
import GraphQLDateTime from "graphql-type-datetime";

export default new GraphQLObjectType({
  name: "DatexTransaction",
  fields: {
    id: { type: GraphQLInt },
    session_time: { type: GraphQLDateTime },
    n_confirmed: { type: GraphQLString },
    t_serial: { type: GraphQLID },
    n_service_station: { type: GraphQLString },
    address: { type: GraphQLString },
    tr_fn_clients: { type: GraphQLString },
    serial_visible: { type: GraphQLString },
    id_vid_trans: { type: GraphQLID },
    n_vid_trans: { type: GraphQLString },
    fn_card_holder: { type: GraphQLString },
    fn_card_owner: { type: GraphQLString },
    confirm_status: { type: GraphQLInt },
    passed: { type: GraphQLInt },
    n_issuers: { type: GraphQLString },
    price: { type: GraphQLFloat },
    amount: { type: GraphQLFloat },
    sum: { type: GraphQLFloat },
    amount_b: { type: GraphQLFloat },
    sum_b: { type: GraphQLFloat },
    discount_type: { type: GraphQLInt },
    discount_value: { type: GraphQLFloat },
    account_struc: { type: GraphQLID },
    n_accounts_struc: { type: GraphQLString },
    n_code: { type: GraphQLString },
    id_account: { type: GraphQLID },
    n_account: { type: GraphQLString },
    n_politics_disconts: { type: GraphQLString },
    ss_fn_clients: { type: GraphQLString },
    discount_amount_v: { type: GraphQLFloat },
    discount_sum_v: { type: GraphQLFloat },
    amount_ok: { type: GraphQLFloat },
    sum_ok: { type: GraphQLFloat },
    sum_azs: { type: GraphQLFloat },
    price_client: { type: GraphQLFloat },
    calc_azs_fn_client: { type: GraphQLString },
    calc_n_service_station: { type: GraphQLString },
    calc_fn_card_owner: { type: GraphQLString },
    lots_amount: { type: GraphQLFloat },
    card_name: { type: GraphQLString },
    is_fuel: { type: GraphQLBoolean },
    version_id: { type: GraphQLInt },
    is_fulld: { type: GraphQLBoolean },
  },
});
