import {
  GraphQLInputObjectType,
  GraphQLString,
  GraphQLInt,
  GraphQLBoolean,
  GraphQLFloat,
  GraphQLList,
} from "graphql";
import GraphQLDateTime from "graphql-type-datetime";

export default new GraphQLInputObjectType({
  name: "DatexPaymentTransactionFilter",
  fields: () => ({
    id: { type: GraphQLInt },
    ids: { type: new GraphQLList(GraphQLInt) },
    id_docums: { type: GraphQLInt },
    session_time: { type: GraphQLDateTime },
    id_vid_docums: { type: GraphQLInt },
    n_docums: { type: GraphQLString },
    d_docums: { type: GraphQLDateTime },
    id_clients: { type: GraphQLInt },
    s_docums: { type: GraphQLFloat },
    price: { type: GraphQLFloat },
    amount: { type: GraphQLFloat },
    status: { type: GraphQLInt },
    accounts: { type: GraphQLInt },
    note: { type: GraphQLString },
    id_transaction: { type: GraphQLInt },
    d_kontr: { type: GraphQLDateTime },
    d_confirm: { type: GraphQLDateTime },
    id_sec_users: { type: GraphQLInt },
    d_expiration: { type: GraphQLDateTime },
    id_source: { type: GraphQLInt },
    id_processing: { type: GraphQLInt },
    external_doc_id: { type: GraphQLString },
    id_vid_pay: { type: GraphQLInt },
    insert_datetime: { type: GraphQLDateTime },
    is_pool_sms: { type: GraphQLBoolean },
    pr_blocked: { type: GraphQLBoolean },
    n_docum_bank: { type: GraphQLString },
    mfo_bank: { type: GraphQLString },
    dt_begin_lot: { type: GraphQLDateTime },
    dt_end_lot: { type: GraphQLDateTime },
    amount_begin: { type: GraphQLFloat },
    amount_doc_sum: { type: GraphQLFloat },
    id_doc_move_accounts: { type: GraphQLInt },
    version_id: { type: GraphQLInt },
  }),
});
